.paket/paket.exe
.vs/fss/v14/.suo
build.fsx
paket.lock
src/Playground/App.config
src/Playground/AssemblyInfo.fs
src/Playground/Playground.fsproj
src/fss/App.config
src/fss/AssemblyInfo.fs
src/fss/fss.fs
src/fss/fss.fsproj
src/fss_mysql/AssemblyInfo.fs
src/fss_mysql/app.config
src/fss_mysql/bin/Debug/Fss_MySql.dll.config
src/fss_mysql/fss_mysql.fsproj
src/fss_postgres/App.config
src/fss_postgres/AssemblyInfo.fs
src/fss_postgres/bin/Debug/FSharp.Core.dll
src/fss_postgres/bin/Debug/FSharp.Core.xml
src/fss_postgres/fss_postgres.fsproj
src/fss_sqlite/App.config
src/fss_sqlite/AssemblyInfo.fs
src/fss_sqlite/C
src/fss_sqlite/fss_sqlite.fsproj
tests/fss.Tests/App.config
tests/fss.Tests/fss.Tests.fsproj
