// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("fss_sqlite")>]
[<assembly: AssemblyProductAttribute("fss")>]
[<assembly: AssemblyDescriptionAttribute("F# Server")>]
[<assembly: AssemblyVersionAttribute("1.6.0")>]
[<assembly: AssemblyFileVersionAttribute("1.6.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "fss_sqlite"
    let [<Literal>] AssemblyProduct = "fss"
    let [<Literal>] AssemblyDescription = "F# Server"
    let [<Literal>] AssemblyVersion = "1.6.0"
    let [<Literal>] AssemblyFileVersion = "1.6.0"
