// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("fss_mysql")>]
[<assembly: AssemblyProductAttribute("fss")>]
[<assembly: AssemblyDescriptionAttribute("F# Server")>]
[<assembly: AssemblyVersionAttribute("1.6.1")>]
[<assembly: AssemblyFileVersionAttribute("1.6.1")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "fss_mysql"
    let [<Literal>] AssemblyProduct = "fss"
    let [<Literal>] AssemblyDescription = "F# Server"
    let [<Literal>] AssemblyVersion = "1.6.1"
    let [<Literal>] AssemblyFileVersion = "1.6.1"
    let [<Literal>] AssemblyConfiguration = "Release"
